### ISSUE TITLE
Unexpected error fetching 991966 data: list index out of range

### ISSUE THREAD

**Issue by auspokey** [yaleman/pyaussiebb#22]
Getting the following error when I load up the integration:

 Logger: homeassistant.components.aussie_broadband
Source: components/aussie_broadband/__init__.py:47
Integration: Aussie Broadband (documentation, issues)
First occurred: March 11, 2022, 10:27:36 PM (790 occurrences)
Last logged: 4:05:19 PM

Unexpected error fetching 991966 data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/aussie_broadband/__init__.py", line 44, in async_update_data
    return await client.get_usage(service_id)
  File "/usr/local/lib/python3.9/site-packages/aussiebb/asyncio/__init__.py", line 323, in get_usage
    self.validate_service_type(service)
  File "/usr/local/lib/python3.9/site-packages/aussiebb/baseclass.py", line 100, in validate_service_type
    raise UnrecognisedServiceType(f"Service type {service['type']} not recognised - please raise an issue about this - https://github.com/yaleman/aussiebb/issues/new")
aussiebb.exceptions.UnrecognisedServiceType: Service type Opticomm not recognised - please raise an issue about this - https://github.com/yaleman/aussiebb/issues/new

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/usr/src/homeassistant/homeassistant/components/aussie_broadband/__init__.py", line 47, in async_update_data
    f"Service {service_id} of type '{services[service_id]['type']}' was unrecognised"
IndexError: list index out of range

**Comment by yaleman** [comment]
Oooh, thanks for reporting this - what services do you have on your account? I'm guessing it's fibre something?

**Comment by auspokey** [comment]
Yep, it is fibre. The service is called opticomm if that helps.

**Comment by Bre77** [comment]
@yaleman Opticomm is one of the private fibre networks that can get deployed in small estates as an alternative to the NBN. I'm hoping it's exactly the same API output as NBN.

This is partially why I used to assume every service was an NBN service until we added VOIP support.

**Comment by yaleman** [comment]
Thanks folks, I'll find some time to fix this in the next week or so.
